version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - "@babel/*"
      jest:
        patterns:
          - "jest"
          - "jest-*"
          - "babel-jest"
          - "@testing-library/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
